version: "3"

services:
  vote:
    build: ./vote
    command: python app.py
    volumes:
     - ./vote:/app
     - bolton:/bolton
    ports:
      - "5000:80"
    networks:
      - front-tier
      - back-tier
    environment:
      - LD_PRELOAD=/bolton/wrap.so
      - WRAP_EVENT_DEST=bolton:12345
      - WRAP_EVENT_QUERY=all

  result:
    build: ./result
    command: nodemon --debug server.js
    volumes:
      - ./result:/app
    ports:
      - "5001:80"
      - "5858:5858"
    networks:
      - front-tier
      - back-tier

  worker:
    build:
      context: ./worker
    networks:
      - back-tier

  redis:
    image: redis:alpine
    container_name: redis
    ports: ["6379"]
    networks:
      - back-tier

  db:
    image: postgres:9.4
    container_name: db
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - back-tier

  bolton:
    image: taktak/bolton-demo
    container_name: bolton
    networks:
      - back-tier
    ports:
      - "9999:9999"
      - "12345:12345"
    environment:
      - BOLTON_ALLOWREMOTE=1
    volumes:
      - bolton:/bolton
    command: bolton -vv daemon

volumes:
  db-data:
  bolton:

networks:
  front-tier:
  back-tier: